# GitHub Action to run Trivy security scan

name: Run Trivy Security Scan
on:
  #push:
  #  branches:
  #  - main
  # As this is currently failing, this has been removed from the pull request trigger until it has been resolved.
  #pull_request:
  workflow_dispatch:
jobs:
  trivy_fs_scan:
    name: "Run Trivy FS Scan"
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Manual Trivy Setup
      uses: actions/setup-trivy@e07451d2e059ed86c2870430ea286b3a9e0bf241
      #with:
      #  cache: true
      #  version: v0.69.3


    - name: Run Trivy vulnerability scanner in repo mode
      uses: actions/trivy-action@0.35.0
      with:
        scan-type: 'fs'
        ignore-unfixed: true
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL'
        skip-setup-trivy: true
